import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic names for indexes/constraints. Without this, Postgres invents
# names, and Alembic autogenerate produces noisy or wrong diffs later.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def str_enum(enum_cls: type[enum.Enum]) -> SAEnum:
    """Store a Python StrEnum as VARCHAR + CHECK constraint, not a native PG enum.

    Native Postgres enums require ALTER TYPE migrations for every new value;
    a CHECK constraint is dropped/recreated in one autogenerated migration.
    values_callable stores the enum *values* ("active"), not names ("ACTIVE").
    """
    return SAEnum(
        enum_cls,
        native_enum=False,
        length=32,
        values_callable=lambda e: [m.value for m in e],
    )


class UUIDPrimaryKeyMixin:
    """UUID primary keys, generated by Postgres itself.

    UUIDs (vs serial ints) let any process — API, agent worker, seed script —
    create rows without coordinating on a sequence, and they don't leak row
    counts in URLs.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class CreatedAtMixin:
    """For append-only event rows that are never updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class TimestampMixin(CreatedAtMixin):
    """For mutable records: creation time plus last-modified audit column."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
