"""customer_data_model

Revision ID: 769268224126
Revises: b7d3f2a91c04
Create Date: 2026-07-27 19:29:55.340780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769268224126'
down_revision: Union[str, None] = 'b7d3f2a91c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_or_services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products_or_services')),
    sa.UniqueConstraint('name', name=op.f('uq_products_or_services_name'))
    )
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=True)
    op.create_table('customer_contacts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.Enum('email', 'phone', name='contacttype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_contacts_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_contacts')),
    sa.UniqueConstraint('contact_type', 'value', name=op.f('uq_customer_contacts_contact_type'))
    )
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False)
    op.create_table('customer_products',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='customerproductstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_products_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products_or_services.id'], name=op.f('fk_customer_products_product_id_products_or_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_products'))
    )
    op.create_index(op.f('ix_customer_products_customer_id'), 'customer_products', ['customer_id'], unique=False)
    # NOTE: autogenerate flagged ix_knowledge_chunks_embedding (HNSW) and
    # ix_knowledge_chunks_fts (FTS GIN expression index) as "removed" because
    # they were hand-written raw SQL in the knowledge_rag migration, not
    # SQLAlchemy Index objects on the model — it can't see them in ORM
    # metadata to know they're still wanted. Dropping them would silently
    # kill vector/full-text search performance, so those two drop_index
    # calls are deliberately omitted here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_products_customer_id'), table_name='customer_products')
    op.drop_table('customer_products')
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts')
    op.drop_table('customer_contacts')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('products_or_services')
    # ### end Alembic commands ###
