"""conversation_customer_id

Revision ID: b4972266f2dd
Revises: 769268224126
Create Date: 2026-07-27 19:34:05.740954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4972266f2dd'
down_revision: Union[str, None] = '769268224126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_foreign_key(op.f('fk_conversations_customer_id_customers'), 'conversations', 'customers', ['customer_id'], ['id'])
    # NOTE: see customer_data_model migration — the two knowledge_chunks
    # indexes are hand-written raw SQL, invisible to ORM-metadata diffing,
    # and autogenerate wrongly wants to drop them here too. Omitted.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_conversations_customer_id_customers'), 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_column('conversations', 'customer_id')
    # ### end Alembic commands ###
