"""initial_schema

Revision ID: 9674ec54019f
Revises: 
Create Date: 2026-07-25 17:36:35.733998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9674ec54019f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'rolled_back', name='agentversionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=False),
    sa.Column('llm_model', sa.String(length=128), nullable=False),
    sa.Column('stt_provider', sa.String(length=64), nullable=False),
    sa.Column('stt_model', sa.String(length=128), nullable=False),
    sa.Column('tts_provider', sa.String(length=64), nullable=False),
    sa.Column('tts_model', sa.String(length=128), nullable=False),
    sa.Column('tts_voice', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('version_label', name=op.f('uq_agent_versions_version_label'))
    )
    op.create_table('provider_configs',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_provider_configs_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('browser', 'phone', name='conversationchannel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', 'abandoned', name='conversationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_conversations_agent_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('room_name', name=op.f('uq_conversations_room_name'))
    )
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('agent_state_events',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.Enum('greeting', 'consent', 'customer_identification', 'issue_discovery', 'information_collection', 'knowledge_retrieval', 'action_proposal', 'user_confirmation', 'tool_execution', 'resolution_confirmation', 'human_handoff', 'completed', 'failed', name='agentstate', native_enum=False, length=32), nullable=True),
    sa.Column('to_state', sa.Enum('greeting', 'consent', 'customer_identification', 'issue_discovery', 'information_collection', 'knowledge_retrieval', 'action_proposal', 'user_confirmation', 'tool_execution', 'resolution_confirmation', 'human_handoff', 'completed', 'failed', name='agentstate', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_state_events_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_state_events'))
    )
    op.create_index('ix_agent_state_events_conversation_created', 'agent_state_events', ['conversation_id', 'created_at'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='turnrole', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('speech_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speech_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_turns_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns')),
    sa.UniqueConstraint('conversation_id', 'turn_index', name=op.f('uq_conversation_turns_conversation_id'))
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_table('turn_latency_metrics',
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('stt_first_partial_ms', sa.Integer(), nullable=True),
    sa.Column('stt_final_ms', sa.Integer(), nullable=True),
    sa.Column('llm_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('llm_total_ms', sa.Integer(), nullable=True),
    sa.Column('tts_first_audio_ms', sa.Integer(), nullable=True),
    sa.Column('total_response_ms', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_turn_latency_metrics_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.id'], name=op.f('fk_turn_latency_metrics_turn_id_conversation_turns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turn_latency_metrics')),
    sa.UniqueConstraint('turn_id', name=op.f('uq_turn_latency_metrics_turn_id'))
    )
    op.create_index(op.f('ix_turn_latency_metrics_conversation_id'), 'turn_latency_metrics', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_latency_metrics_conversation_id'), table_name='turn_latency_metrics')
    op.drop_table('turn_latency_metrics')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index('ix_agent_state_events_conversation_created', table_name='agent_state_events')
    op.drop_table('agent_state_events')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('provider_configs')
    op.drop_table('agent_versions')
    # ### end Alembic commands ###
